version: "3.8"

networks:
  mybridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  aoj-back:
    build:
      context: ../AOJ-BE
    image: aoj-back
    container_name: aoj-back
    environment:
      BE_PORT: "8080"
    networks:
      mybridge:
        ipv4_address: 172.18.0.3
    ports:
      - "8080:8080"
    restart: always

  aoj-front:
    depends_on:
      - aoj-back
    build:
      context: .
      target: dev
    image: aoj-front
    container_name: aoj-front
    environment:
      FE_PORT: "80"
      BE_HOST: "172.18.0.3"
      BE_PORT: "8080"
    volumes:
      - ./src:/workspace/src
    networks:
      mybridge:
        ipv4_address: 172.18.0.2
    ports:
      - "3000:3000"
    restart: always
