version: "3.8"

networks:
  mybridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  docker-front:
    image: wadevs12/aoj-front
    container_name: aoj-front
    environment:
      FE_PORT: "80"
      BE_IP: "172.18.0.3"
      BE_PORT: "8080"
    networks:
      mybridge:
        ipv4_address: 172.18.0.2
    ports:
      - "80:80"
    restart: always
